server:
  port: 8089

spring:
  datasource:
    username: satcatalogdb
    password: satcatalogdb
    url: jdbc:mysql://satcatalogdb.cfl1nlrulmmx.us-east-1.rds.amazonaws.com:3306/satcatalogdb
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true